"use client";

import Link from "next/link";
import ProposalGenerator from "@/components/ProposalGenerator";

export default function Home() {
  // Guest mode is always enabled in the open app

  return (
    <main className="min-h-screen bg-[#0f0f0f] text-gray-100">
      <header className="mx-auto flex w-full max-w-6xl items-center justify-between px-4 pt-6 sm:px-6 lg:px-8">
        <p className="text-sm font-medium uppercase tracking-[0.2em] text-cyan-300">ProposalOS</p>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 rounded-full border border-emerald-400/30 bg-emerald-500/10 px-3 py-1.5">
            <span className="h-2 w-2 rounded-full bg-emerald-400" />
            <span className="text-xs font-medium text-emerald-200">Guest Mode</span>
          </div>
        </div>
      </header>

      <section className="mx-auto w-full max-w-6xl px-4 pt-12 sm:px-6 lg:px-8">
        <div className="rounded-2xl border border-white/10 bg-[#171717] p-8 shadow-xl sm:p-12">
          <h1 className="mt-4 text-3xl font-bold leading-tight sm:text-5xl">
            Stop Sending Generic Proposals. Start Winning Clients.
          </h1>
          <p className="mt-4 max-w-3xl text-sm text-gray-300 sm:text-lg">
            AI analyzes every job post and writes a proposal in your exact voice. Match score
            shows you which jobs to apply for first.
          </p>

          <div className="mt-7 flex w-full flex-col gap-3 sm:flex-row">
            <button
              type="button"
              onClick={() => {
                const element = document.getElementById("generator");
                if (element) {
                  const top = element.getBoundingClientRect().top + window.pageYOffset - 80;
                  window.scrollTo({
                    top,
                    behavior: "smooth",
                  });
                }
              }}
              className="inline-flex items-center justify-center rounded-xl bg-cyan-500 px-6 py-3 text-base font-semibold text-slate-900 transition hover:bg-cyan-400 sm:px-8 sm:py-4 sm:text-lg"
            >
              Try Free Now
            </button>
            <Link
              href="#examples"
              className="inline-flex items-center justify-center rounded-xl border border-white/15 bg-white/5 px-6 py-3 text-base font-medium text-white transition hover:bg-white/10 sm:px-8 sm:py-4 sm:text-lg"
            >
              View Examples
            </Link>
          </div>
        </div>

        {/* Benefits Section */}
        <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
          <div className="rounded-2xl border border-white/10 bg-[#171717] p-6">
            <div className="text-3xl mb-4">🎯</div>
            <h3 className="text-lg font-semibold text-white mb-2">Match Score</h3>
            <p className="text-sm text-gray-300">
              See exactly how well you match each job before applying
            </p>
          </div>
          <div className="rounded-2xl border border-white/10 bg-[#171717] p-6">
            <div className="text-3xl mb-4">🎤</div>
            <h3 className="text-lg font-semibold text-white mb-2">Voice-Matched</h3>
            <p className="text-sm text-gray-300">
              AI learns your writing style and writes in your exact voice
            </p>
          </div>
          <div className="rounded-2xl border border-white/10 bg-[#171717] p-6">
            <div className="text-3xl mb-4">📋</div>
            <h3 className="text-lg font-semibold text-white mb-2">Proposal History</h3>
            <p className="text-sm text-gray-300">
              Keep track of all your proposals in one place
            </p>
          </div>
          <div className="rounded-2xl border border-white/10 bg-[#171717] p-6">
            <div className="text-3xl mb-4">💡</div>
            <h3 className="text-lg font-semibold text-white mb-2">Pain Point Detection</h3>
            <p className="text-sm text-gray-300">
              AI identifies client pain points and addresses them directly
            </p>
          </div>
        </div>
      </section>

      {/* Proposal Generator Section */}
      <section id="generator" className="mx-auto w-full max-w-6xl px-4 pt-20 sm:px-6 lg:px-8">
        <ProposalGenerator isGuest={true} user={null} />
      </section>

      {/* Examples Section */}
      <section id="examples" className="mx-auto w-full max-w-6xl px-4 pt-20 pb-20 sm:px-6 lg:px-8">
        <div className="text-center">
          <h2 className="text-3xl font-bold text-white sm:text-4xl">See It In Action</h2>
          <p className="mt-4 text-lg text-gray-300">
            Real proposals generated by ProposalOS for different job types
          </p>
        </div>

        <div className="mt-12 space-y-8">
          <div className="rounded-2xl border border-white/10 bg-[#171717] p-6 sm:p-8">
            <div className="flex items-start justify-between gap-4">
              <div className="flex-1">
                <h3 className="text-xl font-semibold text-white">React Developer Dashboard</h3>
                <div className="mt-2 flex items-center gap-4">
                  <span className="inline-flex items-center rounded-full border border-emerald-400/20 bg-emerald-500/10 px-3 py-1 text-sm font-medium text-emerald-300">
                    Match: 88%
                  </span>
                  <span className="text-sm text-gray-400">Strong Match</span>
                </div>
                <p className="mt-4 text-gray-300 leading-relaxed">
                  Your dashboard needs to handle real-time data without slowing down — I have built exactly that. Over 3 years I delivered 12 React dashboards with TypeScript and Tailwind, all with live chart updates and JWT auth. I can start Monday and deliver within 2 weeks inside your $500-800 budget. Want to see two similar projects before we begin?
                </p>
              </div>
            </div>
          </div>

          <div className="rounded-2xl border border-white/10 bg-[#171717] p-6 sm:p-8">
            <div className="flex items-start justify-between gap-4">
              <div className="flex-1">
                <h3 className="text-xl font-semibold text-white">Content Writer for SaaS Blog</h3>
                <div className="mt-2 flex items-center gap-4">
                  <span className="inline-flex items-center rounded-full border border-yellow-400/20 bg-yellow-500/10 px-3 py-1 text-sm font-medium text-yellow-300">
                    Match: 75%
                  </span>
                  <span className="text-sm text-gray-400">Good Match</span>
                </div>
                <p className="mt-4 text-gray-300 leading-relaxed">
                  SaaS blogs fail when they sound like documentation. I write content that converts — 3 years writing for B2B SaaS companies, averaging 2,400 words per article with measurable traffic growth. I can deliver your first article within 5 days. Shall I send a relevant writing sample first?
                </p>
              </div>
            </div>
          </div>

          <div className="rounded-2xl border border-white/10 bg-[#171717] p-6 sm:p-8">
            <div className="flex items-start justify-between gap-4">
              <div className="flex-1">
                <h3 className="text-xl font-semibold text-white">Graphic Designer for Brand Identity</h3>
                <div className="mt-2 flex items-center gap-4">
                  <span className="inline-flex items-center rounded-full border border-emerald-400/20 bg-emerald-500/10 px-3 py-1 text-sm font-medium text-emerald-300">
                    Match: 82%
                  </span>
                  <span className="text-sm text-gray-400">Strong Match</span>
                </div>
                <p className="mt-4 text-gray-300 leading-relaxed">
                  A brand identity that looks generic costs more than it saves. I have designed full brand systems for 8 startups — logo, colors, typography, and usage guidelines. Turnaround is 7 days with 3 revision rounds included. Can I show you two brand packages from similar industries?
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section className="mx-auto w-full max-w-6xl px-4 pt-20 pb-20 sm:px-6 lg:px-8">
        <div className="text-center">
          <h2 className="text-3xl font-bold text-white sm:text-4xl">Simple, Transparent Pricing</h2>
          <p className="mt-4 text-lg text-gray-300">
            Start free, upgrade when you need more proposals
          </p>
        </div>

        <div className="mt-12 grid gap-8 sm:grid-cols-3">
          {/* Free Plan */}
          <div className="rounded-2xl border border-white/10 bg-[#171717] p-8">
            <h3 className="text-2xl font-bold text-white">Free</h3>
            <div className="mt-4">
              <span className="text-4xl font-bold text-white">$0</span>
              <span className="text-gray-400">/month</span>
            </div>
            <p className="mt-4 text-gray-300">Perfect for trying out ProposalOS</p>
            <ul className="mt-6 space-y-3">
              <li className="flex items-center gap-3">
                <span className="text-emerald-400">✓</span>
                <span className="text-gray-300">3 proposals per week</span>
              </li>
              <li className="flex items-center gap-3">
                <span className="text-emerald-400">✓</span>
                <span className="text-gray-300">Basic match scoring</span>
              </li>
              <li className="flex items-center gap-3">
                <span className="text-emerald-400">✓</span>
                <span className="text-gray-300">Standard templates</span>
              </li>
            </ul>
            <button className="mt-8 w-full rounded-xl border border-white/20 bg-white/5 px-6 py-3 font-medium text-white transition hover:bg-white/10">
              Current Plan
            </button>
          </div>

          {/* Pro Plan */}
          <div className="rounded-2xl border border-gray-400/30 bg-gray-500/10 p-8 relative opacity-75">
            <div className="absolute -top-4 left-1/2 transform -translate-x-1/2">
              <span className="rounded-full border border-gray-400 bg-gray-500 px-4 py-1 text-sm font-medium text-gray-900">
                Coming Soon
              </span>
            </div>
            <h3 className="text-2xl font-bold text-white">Pro</h3>
            <div className="mt-4">
              <span className="text-4xl font-bold text-white">$19</span>
              <span className="text-gray-400">/month</span>
            </div>
            <p className="mt-4 text-gray-300">For serious freelancers</p>
            <ul className="mt-6 space-y-3">
              <li className="flex items-center gap-3">
                <span className="text-emerald-400">✓</span>
                <span className="text-gray-300">Unlimited proposals</span>
              </li>
              <li className="flex items-center gap-3">
                <span className="text-emerald-400">✓</span>
                <span className="text-gray-300">Advanced match scoring</span>
              </li>
              <li className="flex items-center gap-3">
                <span className="text-emerald-400">✓</span>
                <span className="text-gray-300">Voice matching</span>
              </li>
              <li className="flex items-center gap-3">
                <span className="text-emerald-400">✓</span>
                <span className="text-gray-300">Priority support</span>
              </li>
            </ul>
            <button className="mt-8 w-full rounded-xl border border-white/20 bg-white/5 px-6 py-3 font-medium text-white transition hover:bg-white/10 cursor-not-allowed" disabled>
              Coming Soon
            </button>
          </div>

          {/* Agency Plan */}
          <div className="rounded-2xl border border-gray-400/30 bg-gray-500/10 p-8 relative opacity-75">
            <div className="absolute -top-4 left-1/2 transform -translate-x-1/2">
              <span className="rounded-full border border-gray-400 bg-gray-500 px-4 py-1 text-sm font-medium text-gray-900">
                Coming Soon
              </span>
            </div>
            <h3 className="text-2xl font-bold text-white">Agency</h3>
            <div className="mt-4">
              <span className="text-4xl font-bold text-white">$49</span>
              <span className="text-gray-400">/month</span>
            </div>
            <p className="mt-4 text-gray-300">For agencies and teams</p>
            <ul className="mt-6 space-y-3">
              <li className="flex items-center gap-3">
                <span className="text-emerald-400">✓</span>
                <span className="text-gray-300">Everything in Pro</span>
              </li>
              <li className="flex items-center gap-3">
                <span className="text-emerald-400">✓</span>
                <span className="text-gray-300">Team collaboration</span>
              </li>
              <li className="flex items-center gap-3">
                <span className="text-emerald-400">✓</span>
                <span className="text-gray-300">Custom templates</span>
              </li>
              <li className="flex items-center gap-3">
                <span className="text-emerald-400">✓</span>
                <span className="text-gray-300">API access</span>
              </li>
            </ul>
            <button className="mt-8 w-full rounded-xl border border-white/20 bg-white/5 px-6 py-3 font-medium text-white transition hover:bg-white/10 cursor-not-allowed" disabled>
              Coming Soon
            </button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="mx-auto w-full max-w-6xl px-4 py-12 sm:px-6 lg:px-8">
        <div className="border-t border-white/10 pt-8">
          <div className="flex flex-col gap-8 sm:flex-row sm:items-center sm:justify-between">
            <p className="text-sm text-gray-400">© 2026 ProposalOS. All rights reserved.</p>
            <div className="flex gap-6">
              <Link href="/privacy" className="text-sm text-gray-400 hover:text-white transition-colors">
                Privacy Policy
              </Link>
              <Link href="/" className="text-sm text-gray-400 hover:text-white transition-colors">
                Home
              </Link>
            </div>
          </div>
        </div>
      </footer>
    </main>
  );
}
